[package]
name = "ovs-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-serialize = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
uuid = { version = "1.1.2", features = ["v4"] }

